/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Counter */

#ifndef _Included_com_example_Counter
#define _Included_com_example_Counter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Counter
 * Method:    initializeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_Counter_initializeNative
  (JNIEnv *, jclass);

/*
 * Class:     com_example_Counter
 * Method:    createWindow
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_Counter_createWindow
  (JNIEnv *, jobject);

/*
 * Class:     com_example_Counter
 * Method:    processMessages
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_Counter_processMessages
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
